### ISSUE TITLE
Angular error on Data Source setup

### ISSUE THREAD

**Issue by gaelreyrol** [ovh/ovh-tsl-datasource#10]
Hi,

I experience an error with the latest version (4f9ef49e84abf16e5201c9c8ddfde5cf0b06ab66) of this plugin using Grafana 6.6.0 (5c11bbdfb4).

I don't have much elements to diagnose this error, apparently it comes from Angular. When I try to setup the source it partially shows a form and then show an infinite loader:

![screencast](https://user-images.githubusercontent.com/498465/73751214-ed2f0100-475e-11ea-92b4-c16d75a5d5b9.gif)

Here is a better screenshot of the errors:

![Screenshot from 2020-02-04 15-01-34](https://user-images.githubusercontent.com/498465/73751408-59116980-475f-11ea-92ef-924b21b9e82b.png)

I hope it helps !

Regards

**Comment by aurrelhebert** [comment]
Hello @gaelreyrol  sorry for the delayed ansewer. 
I just made a new version of the TSL datasource for the Grafana 7.0.3 version. 
Let me know if it fix your issue

**Comment by gaelreyrol** [comment]
Thanks ! Yes the issue is fixed !
